services:
  # השירות הקיים שלך - שרת ה-Streamlit
  trainer-app:
    build: .
    container_name: a-eye-app
    ports:
      - "8501:8501"
    volumes:
      - ".:/app"
    stdin_open: true
    tty: true
    init: true

  # השירות החדש - להרצת קבצי פייתון נוספים
  data-processor:
    build: .
    container_name: models_compare_lite
    volumes:
      - ".:/app"
    # כאן אתה מגדיר איזה קובץ להריץ. 
    command: python3 models_compare_lite.py
    stdin_open: true
    tty: true
    init: true
