services:
  # השירות הקיים שלך - שרת ה-Streamlit
  trainer-app:
    build: .
    container_name: a-eye-app
    ports:
      - "8501:8501"
    volumes:
      - ".:/app"
    stdin_open: true
    tty: true
    init: true

  # השירות החדש - להרצת קבצי פייתון נוספים
  data-processor:
    build: .
    container_name: image_proc
    volumes:
      - ".:/app"
    # כאן אתה מגדיר איזה קובץ להריץ. 
    # החלף את 'your_script.py' בשם הקובץ האמיתי שלך
    command: python image_proc.py
    stdin_open: true
    tty: true
    init: true
