
services:
  # השירות של האפליקציה שלנו
  trainer-app:
    build: .
    container_name: a-eye-app
    # פתיחת הפורטים (בדיוק כמו -p)
    ports:
      - "8501:8501"
    # חיבור התיקייה מהמחשב לתוך הדוקר (ה-Mount שדיברנו עליו)
    volumes:
      - ".:/app"
    # מאפשר לנו לראות את הצבעים והלוגים בטרמינל בצורה טובה
    stdin_open: true
    tty: true
    # אתחול חכם של תהליכים (בדיוק כמו --init)
    init: true